acortador/acortador/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('core.urls')),
    path('a/admin/', admin.site.urls),
]

acortador/core/urls.py
from django.urls import path
from .views import CrearAcortador,PaginaEnlace,RedirectEnlace

app_name = 'core'

urlpatterns = [
    path('',CrearAcortador.as_view(),name='inicio'),
    path('<int:pk>/',PaginaEnlace.as_view(),name='detalle'),
    path('<str:codigo>/',RedirectEnlace.as_view(),name='redirect'),
]

acortador/core/models.py
from django.db import models
from django.urls import reverse
from hashids import Hashids
import datetime

# Create your models here.
class EnlaceQuerySet(models.QuerySet):
    def decode_enlace(self, codigo):
        decode = Hashids(min_length=4,alphabet='abcdefghijklmnopqrstuvwxyz').decode(codigo)[0]
        self.filter(pk=decode).update(contador=models.F('contador') + 1)
        return self.filter(pk=decode).first().url

    def total_enlaces(self):
        return self.count()
    
    def total_redirecciones(self):
        return self.aggregate(redirecciones=models.Sum('contador'))

    def fechas(self,pk):
        #values: convierte el query en forma de diccionario
        return self.values('fecha').annotate(
            marzo=models.Sum('contador',filter=models.Q(fecha__gte=datetime.date(2020,3,1),
            fecha__lte=datetime.date(2020,3,31)))
        ).filter(pk=pk)

class Enlace(models.Model):
    url = models.URLField()
    codigo = models.CharField(max_length=8,blank=True)
    fecha = models.DateField(auto_now_add=True)         #se registra la fecha una sola vez
    contador = models.PositiveIntegerField(default=0)   #solo almacenara numero positivos

    enlaces = EnlaceQuerySet.as_manager()   #administrador del modelo

    #sobre escribiremos el metodo class meta el cual contiene propiedades interesantes
    class Meta:
        verbose_name = 'Enlace URL'
        verbose_name_plural = "Enlaces URLS"

    #este metodo devuelve de una forma mas legible de una intancia de un enlace porque sin él traeria un object en vez del nombre del campo
    def __str__(self):
        return f"URL: {self.url} Codigo: {self.codigo}"

    #cada ves que se le llama podemos activar una acción para que se incluya en el guardado
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
        if not self.codigo:
            self.codigo = Hashids(min_length=4,alphabet='abcdefghijklmnopqrstuvwxyz').encode(self.pk)
            self.save()
    
    #como crear una url con base en un objeto
    def get_absolute_url(self):
        return reverse('core:detalle', kwargs={'pk': self.pk})

acortador/core/forms.py
from django import forms
from .models import Enlace

class AcortadorForm(forms.ModelForm):

    class Meta:
        model = Enlace
        fields = ['url']
        widgets = {
            'url':forms.URLInput(
                attrs={
                    'class':'input is-rounded is-medium',
                    'placeholder':'URL'
                }
            )
        }

acortador/core/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.base import RedirectView
from django.views.generic.edit import CreateView

from .forms import AcortadorForm
from .models import Enlace

# Create your views here.
#vamos apoyarnos del siguente link para las vista basadas en clases:
#https://ccbv.co.uk/projects/Django/2.2/



class CrearAcortador(CreateView):
    model = Enlace
    form_class = AcortadorForm
    template_name = "inicio.html"

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs) #renderiza cada elemento en forma de diccionario
        contexto['total_enlaces'] = Enlace.enlaces.total_enlaces()
        contexto['total_redirecciones'] = Enlace.enlaces.total_redirecciones()['redirecciones']
        return contexto


class PaginaEnlace(DetailView):
    model = Enlace
    template_name = "enlace.html"

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['marzo'] = Enlace.enlaces.fechas(self.kwargs['pk'])[0]['marzo']
        return contexto
    

class RedirectEnlace(RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        try:
            return Enlace.enlaces.decode_enlace(self.kwargs['codigo'])
        except IndexError:
            print("Decode sin datos")

acortador/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css">
  <title> {% block titulo %} {% endblock titulo %} </title>
</head>

<body>
{% include 'navbar.html' %}

{% block contenido %}
  
{% endblock contenido %}
</body>

</html>

acortador/templates/enlace.html
{% extends 'base.html' %}

{% block titulo %}
  Enlace 
{% endblock titulo %}

{% block contenido %}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-4 is-offset-4">
        <div class="tags has-addons">
          <a href="{% url 'core:redirect' codigo=object.codigo %}" class="tag is-large">{{request.META.HTTP_HOST}}</a>
          <span class="tag is-info is-large">{{object.codigo}}</span>
        </div>
      </div>
    </div>
    <div class="box">
      <canvas id="myChart"></canvas>
    </div>
  </div>
</section>
<script>
  var ctx = document.getElementById('myChart').getContext('2d');
  var chart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
      datasets: [{
        label: 'Redirecciones',
        backgroundColor: 'rgb(32, 156, 238)',
        borderColor: 'rgb(32, 156, 238)',
        data: [0, 0,"{{marzo}}", 0, 0, 0, 0, 0, 0, 0, 0, 0]
      }]
    },
    options: {}
  })
</script>

{% endblock contenido %}

acortador/templates/inicio.html
{% extends 'base.html' %}

{% block titulo %}
  Acortador URL
{% endblock titulo %}

{% block contenido %}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-4">
        <h1 class="title">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h1>
        <h2 class="subtitle">
          Fusce quis turpis hendrerit, <strong>ultrices</strong> nibh quis, malesuada mauris. Praesent aliquam ligula
          in faucibus
          tempus
        </h2>
        <br>
        <form method="POST">
          {% csrf_token %}
          <div class="field has-addons">
            <div class="control">
              {{form.url}}
            </div>
            <div class="control">
              <input type="submit" class="button is-info is-rounded is-medium" value="Acortar">
            </div>
          </div>
        </form>
      </div>
      <div class="column is-6 is-offset-2">
        <canvas id="myChart"></canvas>
      </div>
    </div>
  </div>
</section>
<script>
  var ctx = document.getElementById('myChart').getContext('2d');
  var chart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ["Enlaces", "Redirecciones"],
      datasets: [
        {
          backgroundColor: ["#8e5ea2", "#3e95cd"],
          data: ["{{total_enlaces}}", "{{total_redirecciones}}"]
        }
      ]
    },
    options: {
      legend: { display: false },
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true
          }
        }]
      }
    }
  });
</script>

{% endblock contenido %}

acortador/templates/navbar.html
<div class="container">
  <nav class="navbar">
    <div class="navbar-menu">
      <div class="navbar-start">
        <a href="{% url 'core:inicio' %}" class="navbar-item" style="padding-left: 0px;">
          Acortador URL
        </a>
      </div>
      <div class="navbar-end">
        <a class="navbar-item">
          Lorem
        </a>
        <a class="navbar-item">
          Lorem
        </a>
        <a class="navbar-item">
          Lorem
        </a>
      </div>
    </div>
  </nav>
</div>